### ISSUE TITLE
New page for each article when printing articles from the article list

### ISSUE THREAD

**Issue by andredevleeschouwer** [ViennaRSS/vienna-rss#1213]
Now it is possible to print a list of articles from the article list towards the printer or towards a pdf file.  However, the printout is continuous.  Would it be possible to put a page break after every article ?  In this way later on articles can easily be extracted from the pdf (or from the printer).  Hopefully this can be done quite rapidly.  I understand that my request #1048 probably may still take some time.

**Comment by barijaona** [comment]
Good news for you : [Vienna styles](http://www.vienna-rss.com/?page_id=65 "Creating Custom Styles") can get all the benefits of [CSS power](https://www.w3schools.com/cssref/pr_print_pagebb.asp "page-break-before property").

As a sample, attached is a modified Tyger style, named "Tyger print". Double click on it and it will install itself automatically (in `~/Library/Application Support/Vienna/Styles` folder)

I just had to add this in the stylesheet.css : 
````CSS
/* when printing, add a page break before start of each article */
@media print {
    .articleTitleStyle {page-break-before: always;}
}
````

Whether this should be standard behavior for default styles provided with Vienna can be discussed.

Attachment : [Tyger print.viennastyle.zip](https://github.com/ViennaRSS/vienna-rss/files/2713885/Tyger.print.viennastyle.zip)
